const CACHE='ichi-1.5.8-build1582-'+self.registration.scope;
const PHOTO_CACHE='ichi-photo-1.5.8-build1582';
const PACKS={english:[...Array.from({length:133},(_,i)=>'./audio/en-'+String(i).padStart(3,'0')+'.mp3'),'./audio/english-manifest.json'],core:['./index.html','./app.js?v=1582','./style.css?v=1582','./travel-data.js?v=1582','./discover.js?v=1582','./places-data.js?v=1582','./discover.css?v=1582'],guide:['./manifest.webmanifest','./icon-192.png','./icon-512.png','./fuji.webp','./joint-kiosk-overview.png','./joint-kiosk-steps.png','./joint-kiosk-rules.png','./joint-kiosk.html',...[400,500,600,700].map(n=>'./fonts/noto-thai-'+n+'.ttf')],maps:['tokyo','osaka','tokyo-jr','kansai'].flatMap(n=>['./maps/'+n+'.webp','./maps/'+n+'.pdf']),audio:[...Array.from({length:133},(_,i)=>'./audio/ja-'+String(i).padStart(3,'0')+'.mp3'),'./audio/manifest.json']};
const url=p=>new URL(p,self.registration.scope).href;
async function put(p){const r=await fetch(url(p),{cache:'reload',credentials:'same-origin'});if(!r.ok||r.redirected)throw Error('ดาวน์โหลดไม่ได้: '+p);if(!p.endsWith('index.html')&&(r.headers.get('content-type')||'').includes('text/html'))throw Error('ได้รับหน้าเข้าสู่ระบบแทนไฟล์: '+p);if(p.endsWith('index.html')){const h=await r.clone().text();if(!h.includes('id="app"')||!h.includes('ICHI-JAPAN'))throw Error('ต้องเปิดแอปและเข้าสู่ระบบขณะออนไลน์ก่อน')}const c=await caches.open(CACHE);await c.put(url(p),r)}
async function status(){const c=await caches.open(CACHE),packs={};for(const [name,files] of Object.entries(PACKS)){const present=await Promise.all(files.map(p=>c.match(url(p))));packs[name]={ready:present.filter(Boolean).length,total:files.length}}return {version:6,packs}}
async function download(port){let done=0;const all=Object.values(PACKS).flat(),failed=[],c=await caches.open(CACHE);let next=0;async function worker(){while(next<all.length){const p=all[next++];try{if(!await c.match(url(p))){const prior=PACKS.core.includes(p)?null:await caches.match(url(p));if(prior)await c.put(url(p),prior);else await put(p)}}catch(e){failed.push(p)}done++;port?.postMessage({type:'PROGRESS',done,total:all.length})}}await Promise.all([worker(),worker(),worker(),worker()]);return {...await status(),failed}}
self.addEventListener('install',e=>e.waitUntil(Promise.all(PACKS.core.map(put))));
self.addEventListener('activate',e=>e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('ichi-')&&k!==CACHE&&k!==PHOTO_CACHE).map(k=>caches.delete(k)));await self.clients.claim()})()));
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING'){e.waitUntil(self.skipWaiting());return}const port=e.ports[0];if(!port)return;e.waitUntil((async()=>{try{const data=e.data?.type==='CACHE_APP'?await download(port):await status();port.postMessage({type:'DONE',ok:true,...data})}catch(err){port.postMessage({type:'DONE',ok:false,error:err.message})}})())});
self.addEventListener('fetch',e=>{const u=new URL(e.request.url),scope=new URL(self.registration.scope);if(e.request.method!=='GET')return;const remotePhoto=/^(?:en\.wikipedia\.org|commons\.wikimedia\.org|upload\.wikimedia\.org|thumb\.wikimedia\.org)$/.test(u.hostname);if(remotePhoto){e.respondWith((async()=>{const c=await caches.open(PHOTO_CACHE),hit=await c.match(e.request);if(hit)return hit;try{const r=await fetch(e.request);if(r&&(r.ok||r.type==='opaque'))await c.put(e.request,r.clone());return r}catch(err){return hit||Response.error()}})());return}if(u.origin!==scope.origin)return;const appNavigation=e.request.mode==='navigate'&&(u.pathname===scope.pathname||u.pathname===new URL('index.html',scope).pathname);if(appNavigation){e.respondWith((async()=>{const c=await caches.open(CACHE),r=await c.match(url('./index.html'));return r||fetch(e.request)})());return}const p=Object.values(PACKS).flat().find(p=>url(p)===u.href);if(p)e.respondWith((async()=>{const c=await caches.open(CACHE),r=await c.match(url(p));if(r)return r;await put(p);return await c.match(url(p))})())});
